import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from '@/context/CartContext';
import { WishlistProvider } from '@/context/WishListContext';
import "./globals.css";
import Navbar from "@/components/home/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <CartProvider>
          <WishlistProvider>
      {children}
      </WishlistProvider>
    </CartProvider>
    
      </body>
    </html>
  );
}
